// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9ECjIQHcBMdM7idm-ZU8ZsoSZt37rtw',
    appId: '1:890986480690:web:bfd1b52b2c03fb4746a82b',
    messagingSenderId: '890986480690',
    projectId: 'omsaravanabhavanhotel-edf79',
    authDomain: 'omsaravanabhavanhotel-edf79.firebaseapp.com',
    storageBucket: 'omsaravanabhavanhotel-edf79.appspot.com',
    measurementId: 'G-ZWK79WFCY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsg4pRM_dj3qWZDr5mW7MZFs5Sg5kcuOo',
    appId: '1:890986480690:android:dd6be82c9bed93d246a82b',
    messagingSenderId: '890986480690',
    projectId: 'omsaravanabhavanhotel-edf79',
    storageBucket: 'omsaravanabhavanhotel-edf79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkP9yLN6lJWfwEkd3N07IubAMcZHc8Og',
    appId: '1:890986480690:ios:e350e5a4bd7e967b46a82b',
    messagingSenderId: '890986480690',
    projectId: 'omsaravanabhavanhotel-edf79',
    storageBucket: 'omsaravanabhavanhotel-edf79.appspot.com',
    iosBundleId: 'com.example.osb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkP9yLN6lJWfwEkd3N07IubAMcZHc8Og',
    appId: '1:890986480690:ios:0255ea980296aff746a82b',
    messagingSenderId: '890986480690',
    projectId: 'omsaravanabhavanhotel-edf79',
    storageBucket: 'omsaravanabhavanhotel-edf79.appspot.com',
    iosBundleId: 'com.example.osb.RunnerTests',
  );
}
