name: om_saravana_bhavan_application
description: "Hotel Saravana Bhavan project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_overlay_loader: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins_bold.ttf
          weight: 700
        - asset: fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: fonts/poppins_medium.ttf
          weight: 500
        - asset: fonts/poppins_regular.ttf
          weight: 400
        - asset: fonts/poppins_light.ttf
          weight: 300

    - family: Sacramento
      fonts:
        - asset: fonts/sacramento_regular.ttf
          weight: 400
  